type AppEnv = {
  /** If true, forgot-password API includes reset token in JSON (dev/testing only). */
  PASSWORD_RESET_RETURN_TOKEN: boolean
  DATABASE_URL: string
  SUPABASE_URL?: string
  SUPABASE_ANON_KEY?: string
  SUPABASE_SERVICE_ROLE_KEY?: string
  JWT_ACCESS_SECRET: string
  JWT_REFRESH_SECRET: string
  JWT_ACCESS_EXPIRES_IN: string
  JWT_REFRESH_EXPIRES_IN: string
  REDIS_URL?: string
  REDIS_PASSWORD?: string
  REDIS_ENABLED?: string
  STORAGE_LOCAL_PATH: string
  CDN_BASE_URL: string
  PAYMENT_PROVIDER_DEFAULT?: string
  PAYMENT_WEBHOOK_SECRET?: string
  RAZORPAY_KEY_ID?: string
  RAZORPAY_KEY_SECRET?: string
  STRIPE_SECRET_KEY?: string
  SHIPROCKET_EMAIL?: string
  SHIPROCKET_PASSWORD?: string
  /** Optional Bearer JWT from Shiprocket auth/login (valid ~10 days). Use instead of email/password. */
  SHIPROCKET_TOKEN?: string
  /** Alias for SHIPROCKET_TOKEN if you store the JWT under a different name. */
  SHIPROCKET_API_KEY?: string
  SHIPROCKET_BASE_URL?: string
  SHIPROCKET_MODE?: string
  SHIPROCKET_WEBHOOK_SECRET?: string
  SHIPROCKET_PICKUP_POSTCODE?: string
  SHIPROCKET_PICKUP_LOCATION?: string
  /** Shiprocket channel id for `/orders/create/return` (numeric string). */
  SHIPROCKET_CHANNEL_ID?: string
  /** Warehouse / hub address for reverse (customer → warehouse) returns. */
  SHIPROCKET_RETURN_SHIPPING_NAME?: string
  SHIPROCKET_RETURN_SHIPPING_ADDRESS?: string
  SHIPROCKET_RETURN_SHIPPING_CITY?: string
  SHIPROCKET_RETURN_SHIPPING_STATE?: string
  SHIPROCKET_RETURN_SHIPPING_PINCODE?: string
  SHIPROCKET_RETURN_SHIPPING_COUNTRY?: string
  SHIPROCKET_RETURN_SHIPPING_PHONE?: string
  SHIPROCKET_RETURN_SHIPPING_EMAIL?: string
  OTP_TTL_SECONDS?: string
  RETURN_WINDOW_DAYS?: string
  OTP_MAX_ATTEMPTS?: string
  OTP_RESEND_COOLDOWN_SECONDS?: string
  SMS_PROVIDER?: string
  SMS_FROM?: string
  SMS_USERNAME?: string
  SMS_API_KEY?: string
  SMS_SENDER_ID?: string
  SMS_BASE_URL?: string
  SMS_TEMPLATE_PASSWORD_RESET?: string
  SMS_TEMPLATE_PAYMENT_CONFIRM?: string
  SMS_TEMPLATE_OTP_VERIFY?: string
  SMS_TEMPLATE_WELCOME?: string
  SMS_TEMPLATE_ORDER_PAID?: string
  SMS_TEMPLATE_LOGIN_OTP?: string
  TWILIO_ACCOUNT_SID?: string
  TWILIO_AUTH_TOKEN?: string
  MSG91_AUTH_KEY?: string
  MSG91_TEMPLATE_ID?: string
  SMTP_HOST?: string
  SMTP_PORT?: string
  SMTP_USER?: string
  SMTP_PASS?: string
  SMTP_FROM?: string
  INTERNAL_JOB_SECRET?: string
  PRISMA_FALLBACK_ENABLED?: string
  SUPABASE_PRODUCTS_WRITE_ENABLED?: string
  UPLOAD_IMAGE_MAX_BYTES?: string
  UPLOAD_IMAGE_THUMB_WIDTH?: string
  UPLOAD_IMAGE_MEDIUM_WIDTH?: string
  UPLOAD_RATE_LIMIT_PER_MIN?: string
  BULK_UPLOAD_RATE_LIMIT_PER_10M?: string
  UPLOAD_MAX_FILES_PER_REQUEST?: string
  DLT_PASSWORD_RESET_ID?: string
  DLT_PASSWORD_RESET_MSG?: string
  DLT_TRANSACTION_ID?: string
  DLT_TRANSACTION_MSG?: string
  DLT_REG_OTP_ID?: string
  DLT_REG_OTP_MSG?: string
  DLT_WELCOME_ID?: string
  DLT_WELCOME_MSG?: string
  DLT_PAYMENT_ID?: string
  DLT_PAYMENT_MSG?: string
  DLT_LOGIN_OTP_ID?: string
  DLT_LOGIN_OTP_MSG?: string
  DLT_ORDER_CONFIRM_ID?: string
  DLT_ORDER_CONFIRM_MSG?: string
  DLT_ORDER_CANCEL_ID?: string
  DLT_ORDER_CANCEL_MSG?: string
}

const getEnv = (key: keyof AppEnv, fallback?: string) => {
  const value = process.env[key] ?? fallback
  if (!value) {
    throw new Error(`Missing required environment variable: ${key}`)
  }
  return value
}

export const env: AppEnv = {
  PASSWORD_RESET_RETURN_TOKEN: process.env.PASSWORD_RESET_RETURN_TOKEN === "true",
  DATABASE_URL: getEnv("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/ziply5_admin?schema=public"),
  SUPABASE_URL: process.env.SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  JWT_ACCESS_SECRET: getEnv("JWT_ACCESS_SECRET", "dev_access_secret"),
  JWT_REFRESH_SECRET: getEnv("JWT_REFRESH_SECRET", "dev_refresh_secret"),
  JWT_ACCESS_EXPIRES_IN: getEnv("JWT_ACCESS_EXPIRES_IN", "1h"),
  JWT_REFRESH_EXPIRES_IN: getEnv("JWT_REFRESH_EXPIRES_IN", "7d"),
  REDIS_URL: process.env.REDIS_URL,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  REDIS_ENABLED: process.env.REDIS_ENABLED,
  STORAGE_LOCAL_PATH: getEnv("STORAGE_LOCAL_PATH", "./storage/uploads"),
  CDN_BASE_URL: getEnv("CDN_BASE_URL", "https://cdn.ziply5.com"),
  PAYMENT_PROVIDER_DEFAULT: process.env.PAYMENT_PROVIDER_DEFAULT,
  PAYMENT_WEBHOOK_SECRET: process.env.PAYMENT_WEBHOOK_SECRET,
  RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  SHIPROCKET_EMAIL: process.env.SHIPROCKET_EMAIL,
  SHIPROCKET_PASSWORD: process.env.SHIPROCKET_PASSWORD,
  SHIPROCKET_TOKEN: process.env.SHIPROCKET_TOKEN,
  SHIPROCKET_API_KEY: process.env.SHIPROCKET_API_KEY,
  SHIPROCKET_BASE_URL: process.env.SHIPROCKET_BASE_URL,
  SHIPROCKET_MODE: process.env.SHIPROCKET_MODE,
  SHIPROCKET_WEBHOOK_SECRET: process.env.SHIPROCKET_WEBHOOK_SECRET,
  SHIPROCKET_PICKUP_POSTCODE: process.env.SHIPROCKET_PICKUP_POSTCODE,
  SHIPROCKET_PICKUP_LOCATION: process.env.SHIPROCKET_PICKUP_LOCATION,
  SHIPROCKET_CHANNEL_ID: process.env.SHIPROCKET_CHANNEL_ID,
  SHIPROCKET_RETURN_SHIPPING_NAME: process.env.SHIPROCKET_RETURN_SHIPPING_NAME,
  SHIPROCKET_RETURN_SHIPPING_ADDRESS: process.env.SHIPROCKET_RETURN_SHIPPING_ADDRESS,
  SHIPROCKET_RETURN_SHIPPING_CITY: process.env.SHIPROCKET_RETURN_SHIPPING_CITY,
  SHIPROCKET_RETURN_SHIPPING_STATE: process.env.SHIPROCKET_RETURN_SHIPPING_STATE,
  SHIPROCKET_RETURN_SHIPPING_PINCODE: process.env.SHIPROCKET_RETURN_SHIPPING_PINCODE,
  SHIPROCKET_RETURN_SHIPPING_COUNTRY: process.env.SHIPROCKET_RETURN_SHIPPING_COUNTRY,
  SHIPROCKET_RETURN_SHIPPING_PHONE: process.env.SHIPROCKET_RETURN_SHIPPING_PHONE,
  SHIPROCKET_RETURN_SHIPPING_EMAIL: process.env.SHIPROCKET_RETURN_SHIPPING_EMAIL,
  OTP_TTL_SECONDS: process.env.OTP_TTL_SECONDS,
  RETURN_WINDOW_DAYS: process.env.RETURN_WINDOW_DAYS,
  OTP_MAX_ATTEMPTS: process.env.OTP_MAX_ATTEMPTS,
  OTP_RESEND_COOLDOWN_SECONDS: process.env.OTP_RESEND_COOLDOWN_SECONDS,
  SMS_PROVIDER: process.env.SMS_PROVIDER,
  SMS_FROM: process.env.SMS_FROM,
  SMS_USERNAME: process.env.SMS_USERNAME,
  SMS_API_KEY: process.env.SMS_API_KEY,
  SMS_SENDER_ID: process.env.SMS_SENDER_ID,
  SMS_BASE_URL: process.env.SMS_BASE_URL || process.env.SMS_API_URL,
  SMS_TEMPLATE_PASSWORD_RESET: process.env.SMS_TEMPLATE_PASSWORD_RESET,
  SMS_TEMPLATE_PAYMENT_CONFIRM: process.env.SMS_TEMPLATE_PAYMENT_CONFIRM,
  SMS_TEMPLATE_OTP_VERIFY: process.env.SMS_TEMPLATE_OTP_VERIFY,
  SMS_TEMPLATE_WELCOME: process.env.SMS_TEMPLATE_WELCOME,
  SMS_TEMPLATE_ORDER_PAID: process.env.SMS_TEMPLATE_ORDER_PAID,
  SMS_TEMPLATE_LOGIN_OTP: process.env.SMS_TEMPLATE_LOGIN_OTP,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  MSG91_AUTH_KEY: process.env.MSG91_AUTH_KEY,
  MSG91_TEMPLATE_ID: process.env.MSG91_TEMPLATE_ID,
  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_PORT: process.env.SMTP_PORT,
  SMTP_USER: process.env.SMTP_USER,
  SMTP_PASS: process.env.SMTP_PASS,
  SMTP_FROM: process.env.SMTP_FROM,
  INTERNAL_JOB_SECRET: process.env.INTERNAL_JOB_SECRET,
  PRISMA_FALLBACK_ENABLED: process.env.PRISMA_FALLBACK_ENABLED,
  SUPABASE_PRODUCTS_WRITE_ENABLED: process.env.SUPABASE_PRODUCTS_WRITE_ENABLED,
  UPLOAD_IMAGE_MAX_BYTES: process.env.UPLOAD_IMAGE_MAX_BYTES,
  UPLOAD_IMAGE_THUMB_WIDTH: process.env.UPLOAD_IMAGE_THUMB_WIDTH,
  UPLOAD_IMAGE_MEDIUM_WIDTH: process.env.UPLOAD_IMAGE_MEDIUM_WIDTH,
  UPLOAD_RATE_LIMIT_PER_MIN: process.env.UPLOAD_RATE_LIMIT_PER_MIN,
  BULK_UPLOAD_RATE_LIMIT_PER_10M: process.env.BULK_UPLOAD_RATE_LIMIT_PER_10M,
  UPLOAD_MAX_FILES_PER_REQUEST: process.env.UPLOAD_MAX_FILES_PER_REQUEST,
  DLT_PASSWORD_RESET_ID: process.env.DLT_PASSWORD_RESET_ID,
  DLT_PASSWORD_RESET_MSG: process.env.DLT_PASSWORD_RESET_MSG,
  DLT_TRANSACTION_ID: process.env.DLT_TRANSACTION_ID,
  DLT_TRANSACTION_MSG: process.env.DLT_TRANSACTION_MSG,
  DLT_REG_OTP_ID: process.env.DLT_REG_OTP_ID,
  DLT_REG_OTP_MSG: process.env.DLT_REG_OTP_MSG,
  DLT_WELCOME_ID: process.env.DLT_WELCOME_ID,
  DLT_WELCOME_MSG: process.env.DLT_WELCOME_MSG,
  DLT_PAYMENT_ID: process.env.DLT_PAYMENT_ID,
  DLT_PAYMENT_MSG: process.env.DLT_PAYMENT_MSG,
  DLT_LOGIN_OTP_ID: process.env.DLT_LOGIN_OTP_ID,
  DLT_LOGIN_OTP_MSG: process.env.DLT_LOGIN_OTP_MSG,
  DLT_ORDER_CONFIRM_ID: process.env.DLT_ORDER_CONFIRM_ID,
  DLT_ORDER_CONFIRM_MSG: process.env.DLT_ORDER_CONFIRM_MSG,
  DLT_ORDER_CANCEL_ID: process.env.DLT_ORDER_CANCEL_ID,
  DLT_ORDER_CANCEL_MSG: process.env.DLT_ORDER_CANCEL_MSG,
}
