export const ROLE_KEYS = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  SELLER: "seller",
  CUSTOMER: "customer",
} as const

export type RoleKey = (typeof ROLE_KEYS)[keyof typeof ROLE_KEYS]

export const permissionsByRole: Record<RoleKey, string[]> = {
  super_admin: ["*"],
  admin: [
    "dashboard.read",
    "products.read",
    "products.create",
    "products.update",
    "products.delete",
    "orders.read",
    "orders.update",
    "cms.read",
    "cms.update",
    "categories.read",
    "categories.create",
    "categories.update",
    "coupons.read",
    "coupons.create",
    "coupons.update",
    "users.read",
    "settings.read",
    "settings.update",
    "tickets.read",
    "tickets.update",
    "reports.read",
    "notifications.read",
    "brands.read",
    "brands.create",
    "tags.read",
    "tags.create",
    "attributes.read",
    "attributes.create",
    "inventory.read",
    "inventory.update",
    "reviews.read",
    "reviews.update",
    "reviews.create",
    "returns.read",
    "returns.update",
    "abandoned.read",
    "promotions.read",
    "promotions.create",
    "promotions.update",
    "finance.read",
    "finance.update",
    "users.create",
    "addresses.read",
    "addresses.write",
  ],
  seller: [
    "dashboard.read",
    "products.read",
    "products.create",
    "products.update",
    "products.delete",
    "orders.read",
    "notifications.read",
    "finance.read",
    "finance.withdraw",
    "returns.read",
    "reviews.read",
    "promotions.read",
    "tags.read",
    "attributes.read",
    "brands.read",
    "inventory.read",
    "inventory.update",
    "addresses.read",
    "addresses.write",
  ],
  customer: [
    "notifications.read",
    "orders.read",
    "addresses.read",
    "addresses.write",
    "reviews.create",
    "returns.create",
  ],
}

export const hasPermission = (role: RoleKey, permission: string) => {
  const allowed = permissionsByRole[role] ?? []
  return allowed.includes("*") || allowed.includes(permission)
}
